import { Book } from '../models/book';

export const BOOKS: Book[] = [
  
  {
  
    "id": 1,
    "title": "Atomic Habits",
    "author": "James Clear",
    "price": 400,
    "stock": 0,
    "discountPercentage": 10,
    "description": "An easy and proven way to build good habits and break bad ones.",
    "thumbnail": "https://covers.openlibrary.org/b/id/12884170-L.jpg",
    "category": "Self-Development",
    "rating": 4.9
  },
  {
    "id": 2,
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen R. Covey",
    "price": 450,
    "stock": 28,
    "discountPercentage": 8,
    "description": "Powerful lessons in personal change and effectiveness.",
    "thumbnail": "https://covers.openlibrary.org/b/id/7833310-L.jpg",
    "category": "Self-Development",
    "rating": 4.8
  },
  {
    "id": 3,
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "price": 480,
    "stock": 22,
    "discountPercentage": 5,
    "description": "A groundbreaking tour of the mind by a Nobel Prize winner.",
    "thumbnail": "https://covers.openlibrary.org/b/id/7895209-L.jpg",
    "category": "Psychology",
    "rating": 4.7
  },
  {
    "id": 4,
    "title": "The Power of Now",
    "author": "Eckhart Tolle",
    "price": 380,
    "stock": 30,
    "discountPercentage": 12,
    "description": "A guide to spiritual enlightenment and living in the present.",
    "thumbnail": "https://covers.openlibrary.org/b/id/2004233-L.jpg",
    "category": "Self-Development",
    "rating": 4.6
  },
  {
    "id": 5,
    "title": "Man's Search for Meaning",
    "author": "Viktor E. Frankl",
    "price": 350,
    "stock": 40,
    "discountPercentage": 15,
    "description": "A Holocaust survivor's profound insights on finding purpose in life.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8267673-L.jpg",
    "category": "Psychology",
    "rating": 4.9
  },
  {
    "id": 6,
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "price": 320,
    "stock": 45,
    "discountPercentage": 18,
    "description": "A magical tale about following your dreams and personal legend.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    "category": "Fiction",
    "rating": 4.7
  },
  {
    "id": 7,
    "title": "Mindset: The New Psychology of Success",
    "author": "Carol S. Dweck",
    "price": 390,
    "stock": 25,
    "discountPercentage": 10,
    "description": "How your mindset can dramatically affect your ability to achieve.",
    "thumbnail": "https://covers.openlibrary.org/b/id/6979234-L.jpg",
    "category": "Psychology",
    "rating": 4.6
  },
  {
    "id": 8,
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "price": 500,
    "stock": 20,
    "discountPercentage": 0,
    "description": "A sweeping narrative of human history from the Stone Age to today.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8231618-L.jpg",
    "category": "Psychology",
    "rating": 4.8
  },
  {
    "id": 9,
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "price": 370,
    "stock": 32,
    "discountPercentage": 12,
    "description": "A counterintuitive approach to living a good life.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8265650-L.jpg",
    "category": "Self-Development",
    "rating": 4.5
  },
  {
    "id": 10,
    "title": "Educated",
    "author": "Tara Westover",
    "price": 420,
    "stock": 28,
    "discountPercentage": 8,
    "description": "A memoir about the transformative power of education.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8526452-L.jpg",
    "category": "Biography",
    "rating": 4.8
  },
  {
    "id": 11,
    "title": "The Four Agreements",
    "author": "Don Miguel Ruiz",
    "price": 340,
    "stock": 38,
    "discountPercentage": 15,
    "description": "A practical guide to personal freedom and wisdom.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8228456-L.jpg",
    "category": "Self-Development",
    "rating": 4.7
  },
  {
    "id": 12,
    "title": "Emotional Intelligence",
    "author": "Daniel Goleman",
    "price": 410,
    "stock": 0,
    "discountPercentage": 10,
    "description": "Why it matters more than IQ for success in life.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8453678-L.jpg",
    "category": "Psychology",
    "rating": 4.6
  },
  {
    "id": 13,
    "title": "The Midnight Library",
    "author": "Matt Haig",
    "price": 380,
    "stock": 30,
    "discountPercentage": 12,
    "description": "A dazzling novel about all the choices that go into a life well lived.",
    "thumbnail": "https://covers.openlibrary.org/b/id/10909258-L.jpg",
    "category": "Fiction",
    "rating": 4.7
  },
  {
    "id": 14,
    "title": "12 Rules for Life",
    "author": "Jordan B. Peterson",
    "price": 440,
    "stock": 22,
    "discountPercentage": 5,
    "description": "An antidote to chaos with profound life lessons.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8267345-L.jpg",
    "category": "Self-Development",
    "rating": 4.5
  },
  {
    "id": 15,
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "price": 390,
    "stock": 35,
    "discountPercentage": 10,
    "description": "Timeless lessons on wealth, greed, and happiness.",
    "thumbnail": "https://covers.openlibrary.org/b/id/10345789-L.jpg",
    "category": "Psychology",
    "rating": 4.8
  },
  {
    "id": 16,
    "title": "Daring Greatly",
    "author": "Brené Brown",
    "price": 400,
    "stock": 26,
    "discountPercentage": 8,
    "description": "How the courage to be vulnerable transforms the way we live.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8455234-L.jpg",
    "category": "Psychology",
    "rating": 4.7
  },
  {
    "id": 17,
    "title": "The Kite Runner",
    "author": "Khaled Hosseini",
    "price": 360,
    "stock": 32,
    "discountPercentage": 15,
    "description": "A powerful story of friendship, redemption, and betrayal.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8235847-L.jpg",
    "category": "Fiction",
    "rating": 4.8
  },
  {
    "id": 18,
    "title": "Grit: The Power of Passion and Perseverance",
    "author": "Angela Duckworth",
    "price": 420,
    "stock": 20,
    "discountPercentage": 0,
    "description": "Why passion and persistence matter more than talent.",
    "thumbnail": "https://covers.openlibrary.org/b/id/7894823-L.jpg",
    "category": "Psychology",
    "rating": 4.6
  },
  {
    "id": 19,
    "title": "The 5 AM Club",
    "author": "Robin Sharma",
    "price": 380,
    "stock": 28,
    "discountPercentage": 12,
    "description": "Own your morning, elevate your life.",
    "thumbnail": "https://covers.openlibrary.org/b/id/10345234-L.jpg",
    "category": "Self-Development",
    "rating": 4.4
  },
  {
    "id": 20,
    "title": "The Silent Patient",
    "author": "Alex Michaelides",
    "price": 350,
    "stock": 40,
    "discountPercentage": 18,
    "description": "A psychological thriller about a woman who stops speaking after murder.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8261567-L.jpg",
    "category": "Fiction",
    "rating": 4.7
  },
  {
    "id": 21,
    "title": "Can't Hurt Me",
    "author": "David Goggins",
    "price": 430,
    "stock": 24,
    "discountPercentage": 8,
    "description": "Master your mind and defy the odds.",
    "thumbnail": "https://covers.openlibrary.org/b/id/6979456-L.jpg",
    "category": "Self-Development",
    "rating": 4.8
  },
  {
    "id": 22,
    "title": "The Body Keeps the Score",
    "author": "Bessel van der Kolk",
    "price": 480,
    "stock": 18,
    "discountPercentage": 5,
    "description": "Brain, mind, and body in the healing of trauma.",
    "thumbnail": "https://covers.openlibrary.org/b/id/7884234-L.jpg",
    "category": "Psychology",
    "rating": 4.9
  },
  {
    "id": 23,
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "price": 370,
    "stock": 30,
    "discountPercentage": 10,
    "description": "A moving story about a girl living in Nazi Germany.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8526345-L.jpg",
    "category": "Fiction",
    "rating": 4.8
  },
  {
    "id": 24,
    "title": "Deep Work",
    "author": "Cal Newport",
    "price": 410,
    "stock": 22,
    "discountPercentage": 12,
    "description": "Rules for focused success in a distracted world.",
    "thumbnail": "https://covers.openlibrary.org/b/id/8267891-L.jpg",
    "category": "Self-Development",
    "rating": 4.6
  },
  {
    "id": 25,
    "title": "The Gifts of Imperfection",
    "author": "Brené Brown",
    "price": 360,
    "stock": 35,
    "discountPercentage": 15,
    "description": "Let go of who you think you're supposed to be and embrace who you are.",
    "thumbnail": "https://covers.openlibrary.org/b/id/10909123-L.jpg",
    "category": "Psychology",
    "rating": 4.7
  }
]